### ISSUE TITLE
ValueError: kth(=-1) out of bounds (2)

### ISSUE THREAD

**Issue by AdnanMuhib** [mrdogan7/bug-localization-by-dnn-and-rvsm#2]
Hi @hacetin and @mrdogan7 ,
Can you please have a look at the error and guide me to fix this.
I guess it has something to do with `numpy` can you please tell me the version of numpy you used for your experiment.
Thanks

`python` = `3.5.4`
`numpy` = `1.16.3`
Feature File Sample: 
[our_features.zip](https://github.com/mrdogan7/bug-localization-by-dnn-and-rvsm/files/3143912/our_features.zip)

`>python rvsmModel.py`
```
Traceback (most recent call last):
  File "rvsmModel.py", line 46, in <module>
    max_indices = np.argpartition(relevancy_list, -i)[-i:]
  File "C:\Program Files\Anaconda2\envs\tensorflow\lib\site-packages\numpy\core\fromnumeric.py", line 808, in argpartition
    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
  File "C:\Program Files\Anaconda2\envs\tensorflow\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: kth(=-1) out of bounds (2)
```
<br>

``>python dnnModel.py``

<br>

```
Experiment Counter 1
{'bundles\\org.eclipse.e4.ui.di\\src\\org\\eclipse\\e4\\ui\\di\\Focus.java': [0.076441868, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench\\src\\org\\eclipse\\e4\\ui\\internal\\workbench\\PartServiceImpl.java': [0.022548095, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\e4\\compatibility\\CompatibilityPart.java': [0.005073752, 0.0, 0.0, 0.0, 0.0]}
{'examples\\org.eclipse.e4.demo.contacts\\src\\org\\eclipse\\e4\\demo\\contacts\\views\\DetailsView.java': [0.004814846, 0.0, 0.0, 0.0, 0.0]}
{'examples\\org.eclipse.e4.demo.contacts\\src\\org\\eclipse\\e4\\demo\\contacts\\views\\ListView.java': [0.010916641, 0.0, 0.0, 0.0, 0.0]}
{'examples\\org.eclipse.e4.demo.e4photo\\src\\org\\eclipse\\e4\\demo\\e4photo\\ExifTable.java': [0.02028741, 0.0, 0.0, 0.0, 0.0]}
{'examples\\org.eclipse.e4.demo.e4photo\\src\\org\\eclipse\\e4\\demo\\e4photo\\Library.java': [0.019230336, 0.0, 0.0, 0.0, 0.0]}
{'examples\\org.eclipse.e4.demo.e4photo\\src\\org\\eclipse\\e4\\demo\\e4photo\\Preview.java': [0.004529077, 0.0, 0.0, 0.0, 0.0]}
{'examples\\org.eclipse.e4.demo.e4photo\\src\\org\\eclipse\\e4\\demo\\e4photo\\Thumbnails.java': [0.015073651, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.tests\\src\\org\\eclipse\\e4\\ui\\tests\\application\\ClientEditor.java': [0.015014119, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.tests\\src\\org\\eclipse\\e4\\ui\\tests\\application\\EPartServiceTest.java': [0.000243562, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\dialogs\\ImportExportPage.java': [0.056739584, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\model\\ContributionComparator.java': [0.05388882, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\AbstractSelectionService.java': [0.041155157, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\decorators\\DecorationScheduler.java': [0.040430418, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\decorators\\DecoratorManager.java': [0.038959257, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\menus\\UIElement.java': [0.038376327, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.renderers.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\renderers\\swt\\StackRenderer.java': [0.037344691, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\actions\\OpenNewWindowMenu.java': [0.034056502, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\actions\\OpenNewPageMenu.java': [0.032364138, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.renderers.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\renderers\\swt\\HandledMenuItemRenderer.java': [0.029487313, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\model\\BaseWorkbenchContentProvider.java': [0.027577323, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench.edit\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\advanced\\provider\\AdvancedItemProviderAdapterFactory.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench.edit\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\provider\\MenuContributionItemProvider.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\commands\\impl\\CommandsFactoryImpl.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\commands\\util\\CommandsAdapterFactory.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\commands\\util\\CommandsSwitch.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\descriptor\\basic\\impl\\BasicFactoryImpl.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\descriptor\\basic\\util\\BasicAdapterFactory.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\descriptor\\basic\\util\\BasicSwitch.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\impl\\ApplicationFactoryImpl.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\advanced\\impl\\AdvancedFactoryImpl.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\advanced\\util\\AdvancedAdapterFactory.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\advanced\\util\\AdvancedSwitch.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\basic\\impl\\BasicFactoryImpl.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\basic\\util\\BasicAdapterFactory.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\basic\\util\\BasicSwitch.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\impl\\UiFactoryImpl.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\MMenuContribution.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\impl\\MenuContributionImpl.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\impl\\MenuFactoryImpl.java': [0.007850986, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\impl\\MenuPackageImpl.java': [0.003533245, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\util\\MenuAdapterFactory.java': [0.002499789, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\util\\MenuSwitch.java': [0.003314133, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\util\\UiAdapterFactory.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\util\\UiSwitch.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\util\\ApplicationAdapterFactory.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\util\\ApplicationSwitch.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\internal\\workbench\\swt\\PartRenderingEngine.java': [0.07310537, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\swt\\modeling\\MenuService.java': [0.057791552, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\swt\\modeling\\MenuServiceFilter.java': [0.258393765, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\swt\\modeling\\RunAway.java': [0.073739216, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\menus\\IMenuService.java': [0.095247578, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\actions\\OpenNewPageMenu.java': [0.063065872, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\help\\WorkbenchHelp.java': [0.044656878, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.renderers.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\renderers\\swt\\DirectMenuItemRenderer.java': [0.024138035, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.renderers.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\renderers\\swt\\PerspectiveRenderer.java': [0.018416201, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\registry\\IActionSet.java': [0.015340877, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\part\\DrillDownAdapter.java': [0.014425563, 0.0, 0.0, 0.0, 0.0]}
{'examples\\org.eclipse.e4.ui.examples.css.rcp\\src\\org\\eclipse\\e4\\ui\\examples\\css\\rcp\\ApplicationActionBarAdvisor.java': [0.012134171, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\keys\\IKeyFormatter.java': [0.011542695, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\impl\\MenuFactoryImpl.java': [0.007850986, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\dialogs\\FilteredList.java': [0.006454844, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench.edit\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\provider\\ToolControlItemProvider.java': [0.005586537, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\dialogs\\ElementTreeSelectionDialog.java': [0.004606722, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\util\\MenuSwitch.java': [0.003314133, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\IStartup.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\keys\\KeysPreferenceFiltersDialog.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\progress\\JobTreeElement.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.css.core\\src\\org\\eclipse\\e4\\ui\\css\\core\\utils\\ClassUtils.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.css.swt\\src\\org\\eclipse\\e4\\ui\\css\\swt\\properties\\custom\\CSSPropertyWebbyStyleHandler.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\internal\\workbench\\swt\\Policy.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.tests.css.core\\src\\org\\eclipse\\e4\\ui\\tests\\css\\core\\Activator.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\registry\\IActionSetDescriptor.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\IWorkingSetManager.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\commands\\KeyConfigurationEvent.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\actions\\HelpContentsAction.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.css.core\\src\\org\\eclipse\\e4\\ui\\css\\core\\dom\\ElementAdapter.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.css.core\\src\\org\\eclipse\\e4\\ui\\css\\core\\impl\\dom\\CSSUnknownRuleImpl.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\services\\WorkbenchLocationService.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\registry\\ActionSetDescriptor.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.tests\\src\\org\\eclipse\\e4\\ui\\tests\\reconciler\\xml\\XMLModelReconcilerWindowTest.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\ActionExpression.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\Workbench.java': [0.011467953, 0.0, 0.005199695, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\IEditorPart.java': [0.045452322, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\e4\\compatibility\\SelectionService.java': [0.039720364, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\application\\WorkbenchAdvisor.java': [0.074650764, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench\\src\\org\\eclipse\\e4\\workbench\\ui\\internal\\EMFDeltaMapSet.java': [0.058698686, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench\\src\\org\\eclipse\\e4\\workbench\\ui\\internal\\XMLModelReconciler.java': [0.04737972, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.tests\\src\\org\\eclipse\\e4\\ui\\tests\\reconciler\\ModelReconcilerContributionTest.java': [0.007275464, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench\\src\\org\\eclipse\\e4\\ui\\internal\\workbench\\EMFModelDeltaSet.java': [0.064363774, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\PlaceholderContributionItem.java': [0.053400281, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\BundleGroupProperties.java': [0.052568423, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.renderers.swt\\src\\org\\eclipse\\e4\\workbench\\ui\\renderers\\swt\\SWTPartRenderer.java': [0.005325237, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\swt\\internal\\PartRenderingEngine.java': [0.002537088, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\swt\\internal\\ResourceUtility.java': [0.049562105, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\swt\\util\\ISWTResourceUtilities.java': [0.038424552, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench\\src\\org\\eclipse\\e4\\workbench\\ui\\IResourceUtilities.java': [0.037671148, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\registry\\ViewDescriptor.java': [0.007273817, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.tests\\src\\org\\eclipse\\e4\\ui\\tests\\application\\UIStartupTest.java': [0.004750063, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\dialogs\\AdaptableForwarder.java': [0.057637667, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.css.core\\src\\org\\eclipse\\e4\\ui\\css\\core\\impl\\dom\\CSSRuleListImpl.java': [0.040525495, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\MExpression.java': [0.036619775, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\menu\\MMenuSeparator.java': [0.036288405, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.tests\\src\\org\\eclipse\\e4\\ui\\tests\\reconciler\\xml\\XMLModelReconcilerPartDescriptorTest.java': [0.034473009, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.model.workbench\\src\\org\\eclipse\\e4\\ui\\model\\application\\ui\\basic\\MTrimBar.java': [0.033925838, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.css.core\\src\\org\\eclipse\\e4\\ui\\css\\core\\dom\\CSSExtendedProperties.java': [0.032197712, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.css.core\\src\\org\\eclipse\\e4\\ui\\css\\core\\engine\\CSSErrorHandler.java': [0.03197178, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\IEditorActionDelegate.java': [0.026874794, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\services\\IServiceLocatorCreator.java': [0.068045586, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\plugin\\AbstractUIPlugin.java': [0.05895467, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\application\\DisplayAccess.java': [0.092817037, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.css.swt\\src\\org\\eclipse\\e4\\ui\\css\\swt\\selectors\\DynamicPseudoClassesSWTButtonSelectedHandler.java': [0.038632062, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench\\src\\org\\eclipse\\e4\\workbench\\ui\\internal\\UIEventPublisher.java': [0.041980917, 0.0, 0.074789505, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.bindings\\src\\org\\eclipse\\e4\\ui\\bindings\\keys\\OutOfOrderListener.java': [0.132464919, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.bindings\\src\\org\\eclipse\\e4\\ui\\bindings\\EBindingService.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.services\\src\\org\\eclipse\\e4\\ui\\internal\\services\\ActiveContextsFunction.java': [0.008460774, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\swt\\internal\\PartRenderingEngine.java': [0.003455666, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\workbench\\swt\\internal\\ShellActivationListener.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\application\\ActionBarAdvisor.java': [0.001321923, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\EditorReference.java': [0.0019486, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\WorkbenchWindow.java': [0.002646416, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\e4\\compatibility\\CompatibilityEditor.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\e4\\compatibility\\CompatibilityPart.java': [0.002958554, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\operations\\RedoActionHandler.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\operations\\UndoActionHandler.java': [0.0, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.css.swt\\src\\org\\eclipse\\e4\\ui\\css\\swt\\resources\\SWTResourcesRegistry.java': [0.068003252, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\wizards\\preferences\\PreferencesImportWizard.java': [0.029404338, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.tests\\src\\org\\eclipse\\e4\\ui\\tests\\application\\ResourceHandlerTest.java': [0.025898456, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\layout\\TrimDragPreferenceDialog.java': [0.025188708, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\dialogs\\FileEditorsPreferencePage.java': [0.019991912, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\IEditorActionBarContributor.java': [0.01550678, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\application\\WorkbenchWindowAdvisor.java': [0.015182553, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.tests.css.swt\\tkuiTestsToRefactor\\swt\\test\\org\\akrogen\\tkui\\css\\core\\examples\\csseditors\\AbstractCSSEditor.java': [0.014585013, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.ui.workbench.swt\\src\\org\\eclipse\\e4\\ui\\internal\\workbench\\swt\\E4Application.java': [0.013496765, 0.0, 0.0, 0.0, 0.0]}
{'tests\\org.eclipse.e4.ui.compatibility.tests\\src\\org\\eclipse\\e4\\ui\\compatibility\\tests\\views\\SampleView.java': [0.01198483, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\WorkbenchPage.java': [0.009876152, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.e4.core.commands\\src\\org\\eclipse\\e4\\core\\commands\\internal\\HandlerServiceImpl.java': [0.002312459, 0.0, 0.0, 0.0, 0.0]}
{'bundles\\org.eclipse.ui.workbench\\Eclipse UI\\org\\eclipse\\ui\\internal\\dialogs\\AdaptableForwarder.java': [0.026435635, 0.0, 0.0, 0.0, 0.0]}
Traceback (most recent call last):
  File "dnnModel.py", line 122, in <module>
    max_indices = np.argpartition(relevancy_list, -i)[-i:]
  File "C:\Program Files\Anaconda2\envs\tensorflow\lib\site-packages\numpy\core\fromnumeric.py", line 808, in argpartition
    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
  File "C:\Program Files\Anaconda2\envs\tensorflow\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: kth(=-1) out of bounds (2)
```

**Comment by hacetin** [comment]
I can't see any problem. I tried it on a completely new computer, and it works. Try to use `features.csv` given below.
[features.zip](https://github.com/mrdogan7/bug-localization-by-dnn-and-rvsm/files/3144227/features.zip)

I use `NumPy  1.16.2` and `Python 3.7.3` with Anaconda.

**Comment by AdnanMuhib** [comment]
Thank you very much @hacetin ,
same code worked with your provided features file. 👍 
I am facing issue to generate feature file same as you provided but there is some FileNotFoundError I have mentioned in [comment](https://github.com/mrdogan7/bug-localization-by-dnn-and-rvsm/issues/1#issuecomment-489271686).
